=== FZJ-INM1-BDA/siibra-compose/siibra-compose-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "config": {
            "allOf": [
                {
                    "$ref": "#/definitions/hasRef"
                }
            ]
        },
        "python": {
            "allOf": [
                {
                    "$ref": "#/definitions/hasRef"
                }
            ]
        },
        "api": {
            "allOf": [
                {
                    "$ref": "#/definitions/hasRef"
                }
            ],
            "type": "object",
            "properties": {
                "port": {
                    "type": "number",
                    "default": 10081,
                    "description": "Port which siibra-api will run on"
                },
                "redis": {
                    "type": "object",
                    "properties": {
                        "port": {
                            "type": "number",
                            "default": 6379,
                            "description": "Port which redis will be run on"
                        },
                        "disabled": {
                            "type": "boolean",
                            "default": false,
                            "description": "If Redis will be disabled"
                        }
                    }
                }
            }
        },
        "explorer": {
            "allOf": [
                {
                    "$ref": "#/definitions/hasRef"
                }
            ],
            "properties": {
                "port": {
                    "type": "number",
                    "default": 8080,
                    "description": "Port by which siibra-explorer will run."
                }
            }
        },
        "version": {
            "const": "0.0.1"
        }
    },
    "definitions": {
        "hasRef": {
            "type": "object",
            "properties": {
                "ref": {
                    "type": "string",
                    "description": "PATH to git repo or REFTAG"
                }
            }
        }
    }
}

=== FZJ-INM1-BDA/siibra-compose/siibra-compose.json
{
    "$schema": "./siibra-compose-schema.json",
    "version": "0.0.1",
    "config": {
        "ref": "/home/xiao/dev/projects/siibra-configurations"
    },
    "python": {
        "ref": "/home/xiao/dev/projects/siibra-python"
    },
    "api": {
        "port": 10081,
        "ref": "/home/xiao/dev/projects/siibra-api",
        "redis": {
            "port": 6379,
            "disabled": true
        }
    },
    "explorer": {
        "port": 8080,
        "ref": "/home/xiao/dev/projects/siibra-explorer"
    }
}
